import { verify } from "crypto";
import { User } from "lucide-react";
import Dispatch from "../components/pages/Dispatch";

const url = process.env.NEXT_PUBLIC_BACKEND_END;
const API_END_POINTS = {
  // Custom Methods
  // Standard Methods
  login: `${url}/api/method/vms.APIs.authentication_api.login.login`,
  otpEmail: `${url}/api/method/vms.APIs.authentication_api.send_otp.send_otp`,
  verifyOtp: `${url}/api/method/vms.vms.doctype.otp_verification.otp_verification.verify_otp_and_delete`,
  changePassword: `${url}/api/method/vms.APIs.authentication_api.login.reset_pwd`,
  vendorRegistrationDropdown: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_registration_masters.vendor_registration_dropdown_masters`,
  companyBasedDropdown: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_field_details.get_purchase_team_details`,
  purchaseGroupBasedDropdown: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_field_details.account_group_details`,
  vendorRegistrationSubmit: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_registration.vendor_registration`,
  vendorOnboardingDetail: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_onboarding_get_data.get_vendor_onboarding_data`,
  companyDetailDropdown: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_registration_masters.vendor_onboarding_company_dropdown_master`,
  companyDetailSubmit: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_company_details.update_vendor_onboarding_company_details`,
  companyAddressSubmit: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_company_details.update_vendor_onboarding_company_address`,
  companyAddressDropdown: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_registration_masters.all_address_masters`,
  districtchangeUrl: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_registration_masters.address_filter`,
  contactDetailSubmit: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_contact_details.update_vendor_onboarding_contact_details`,
  manufacturingDetailSubmit: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_manufacturing_details.update_vendor_onboarding_manufacturing_details`,
  employeeDetailSubmit: `${url}/api/method/vms.APIs.vendor_onboarding.production_facility.update_vendor_onboarding_production_facility_details`,
  machineDetailSubmit: `${url}/api/method/vms.APIs.vendor_onboarding.production_facility.update_vendor_onboarding_machinery_detail`,
  testingDetailSubmit: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_testing_details.update_vendor_onboarding_testing_details`,
  reputedDetailSubmit: `${url}/api/method/vms.APIs.vendor_onboarding.reputed_company_details.update_vendor_onboarding_reputed_company_details`,
  certifcateCodeDropdown: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_certificate_details.vendor_certificate_name_masters`,
  certificateSave: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_certificate_details.update_vendor_onboarding_certificate_details`,
  bankNameDropdown: `${url}/api/method/vms.APIs.master_apis.get_bank_master.get_bank_list`,
  bankSubmit: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_payment_details.update_vendor_onboarding_payment_details`,
  currencyDropdown: `${url}/api/method/vms.APIs.master_apis.get_currency.get_currency_list`,
  documentDetailSubmit: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_document_details.update_vendor_onboarding_document_details`,
  fetchDetails: `${url}/api/method/vms.APIs.vendor_onboarding.get_full_data_of_ven_onboarding.get_vendor_onboarding_details`,
  fetchimportedvendordetails: `${url}/api/method/vms.APIs.dashboard_api.get_full_import_vendors_data.get_full_data_of_import_vendors`,
  documentDetail_dropdown: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_registration_masters.vendor_onboarding_document_dropdown_master`,
  deleteCertificate: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_certificate_details.delete_vendor_onboarding_certificate_row`,
  dashboardCardURL: `${url}/api/method/vms.APIs.dashboard_api.po_pi_gen_api.dashboard_card`,
  dashboardPOTableURL: `${url}/api/method/vms.APIs.dashboard_api.po_data.get_po`,
  dashboardTableURL: `${url}/api/method/vms.APIs.dashboard_api.filter_card.get_vendors_based_on_status`,
  getPoDetailURL: `${url}/api/method/vms.APIs.dashboard_api.po_data.get_po_details`,
  dashboardTotalVendorTableURL: `${url}/api/method/vms.APIs.dashboard_api.dashboard_filters_data.total_vendor_details`,
  dashboardPendingVendorTableURL: `${url}/api/method/vms.APIs.dashboard_api.dashboard_filters_data.pending_vendor_details`,
  dashboardApprovedVendorTableURL: `${url}/api/method/vms.APIs.dashboard_api.dashboard_filters_data.approved_vendor_details`,
  dashboardRejectedVendorTableURL: `${url}/api/method/vms.APIs.dashboard_api.dashboard_filters_data.rejected_vendor_details`,
  certificateSubmit: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_registration.onboarding_form_submit`,
  logout: `${url}/api/method/logout`,
  companyDropdown: `${url}/api/resource/Company%20Master`,
  reconsiliationDropdown: `${url}/api/method/vms.APIs.master_apis.get_reconcilation_account.get_reconcilation_list`,
  mobileCodeBasedOnCountry: `${url}/api/method/vms.APIs.master_apis.get_country.country_details`,
  vendorPOTable: `${url}/api/method/vms.APIs.vendors_dashboards_api.get_vendor_details_for_dashboard.get_po_from_vendor_code`,
  vendorCodeDialogApi: `${url}/api/method/vms.APIs.dashboard_api.get_vendor_code.collect_vendor_code_data`,
  VendorCodeBasedCardCount: `${url}/api/method/vms.APIs.vendors_dashboards_api.get_vendor_details_for_dashboard.get_po_count_from_vendor_code`,
  vendorPurchaseRequestDropdown: `${url}/api/method/vms.APIs.purchase_api.create_pr.purchase_requsition_masters`,
  submitPR: `${url}/api/method/vms.APIs.purchase_api.create_pr.create_purchase_requisition`,
  getPRData: `${url}/api/method/vms.APIs.dashboard_api.po_pi_gen_api.get_pr_w_details`,
  getInquiryDropdown: `${url}/api/method/vms.APIs.purchase_api.purchase_inquiry.cart_details_masters`,
  fetchProductNameBasedOnCategory: `${url}/api/method/vms.APIs.purchase_api.purchase_inquiry.filter_product_name`,
  submitPrInquiryNextButton: `${url}/api/method/vms.APIs.purchase_api.purchase_inquiry.create_purchase_inquiry`,
  prInquiryCount: `${url}/api/method/vms.APIs.dashboard_api.po_pi_gen_api.dashboard_card`,
  prInquiryDashboardTable: `${url}/api/method/vms.APIs.dashboard_api.po_pi_gen_api.get_pi`,
  prInquiryData: `${url}/api/method/vms.APIs.dashboard_api.po_pi_gen_api.get_pi_details`,
  prInquiryHodApproval: `${url}/api/method/vms.APIs.purchase_api.purchase_inquiry_approvals.hod_approval_check`,
  prInquiryPurchaseApproval: `${url}/api/method/vms.APIs.purchase_api.purchase_inquiry_approvals.purchase_approval_check`,
  prTableData: `${url}/api/method/vms.APIs.dashboard_api.po_pi_gen_api.get_pr_w`,
  qmsformdetails: `${url}/api/method/vms.APIs.assessment_apis.qms_api.get_qms_details_without_label`,
  qmsformapproval: `${url}/api/method/vms.APIs.assessment_apis.qms_api.approve_qms_form`,
  qmsformsubmit: `${url}/api/method/vms.APIs.assessment_apis.save_qms_assessment.save_qms_assessment_complete`,
  qmstablemultiselect: `${url}/api/method/vms.APIs.assessment_apis.get_or_create_qms_multiselect_data.get_all_multiselect_masters`,
  qmsqadocumenttypelist: `${url}/api/method/vms.APIs.assessment_apis.get_or_create_qms_multiselect_data.get_quality_agreement_list`,
  poBasedOnVendorCode: `${url}/api/method/vms.APIs.purchase_api.dispatch_item.list_purchase_order`,
  PODetailsBasedOnPOCode: `${url}/api/method/vms.APIs.purchase_api.dispatch_item.get_poitem_against_po`,
  PurchaseEnquiryModify: `${url}/api/method/vms.APIs.purchase_api.purchase_inquiry.modified_peq`,
  PurchaseEnquiryAcknowledge: `${url}/api/method/vms.APIs.purchase_api.purchase_inquiry.acknowledge_purchase_inquiry`,
  saveDraftDispatch: `${url}/api/method/vms.APIs.purchase_api.dispatch_item.update_dispatch_item`,
  InquirycompanyBasedOnUser: `${url}/api/method/vms.APIs.purchase_api.purchase_inquiry.get_company_for_pe_detailed`,
  InquiryPurchaseTypeDropdown: `${url}/api/method/vms.APIs.purchase_api.purchase_inquiry.get_purchase_type`,
  InquiryDropdownsBasedOnCompany: `${url}/api/method/vms.APIs.purchase_api.purchase_inquiry.get_plants_and_purchase_group`,
  AddDispatch: `${url}/api/method/vms.APIs.purchase_api.dispatch_item.update_dispatch_item`,
  SubmitDispatch: `${url}/api/method/vms.APIs.purchase_api.dispatch_item.submit_dispatch_item`,
  dispatchDetails: `${url}/api/method/vms.APIs.purchase_api.dispatch_item.full_data_dispatch_item`,
  dispatchTableRowSubmit: `${url}/api/method/vms.APIs.purchase_api.dispatch_item.submit_child_dispatch_item`,
  asaformDetails: `${url}/api/method/vms.APIs.assessment_apis.asa.get_asa_details_without_label`,
  dispatchTable: `${url}/api/method/vms.APIs.dispatch_dashboard.dispatch_dashboard.dispatch_dashboard`,
  poTable: `${url}/api/method/vms.APIs.dashboard_api.filter_card.filtering_po_details`,

  //pr api atul
  fetchDataCartId: `${url}/api/method/vms.APIs.purchase_api.purchase_requisition.get_cart_details`,
  createPR: `${url}/api/method/vms.APIs.purchase_api.purchase_requisition.create_purchase_requisition`,
  fetchPRTableData: `${url}/api/method/vms.APIs.purchase_api.purchase_requisition.get_pur_req_table_data`,
  PRTableHeadSubmitData: `${url}/api/method/vms.APIs.purchase_api.purchase_requisition.update_pr_table_head_form`,
  PRTableSubHeadSubmitData: `${url}/api/method/vms.APIs.purchase_api.purchase_requisition.create_pr_table_subhead_form`,
  PrSubHeadDeleteRow: `${url}/api/method/vms.APIs.purchase_api.purchase_requisition.delete_pr_table_row`,
  SubmitPR: `${url}/api/method/vms.APIs.purchase_api.purchase_requisition.submit_pr_form`,
  getPRItemsTable: `${url}/api/method/vms.APIs.grn_apis.all_grn_details.get_pr_details_simple`,

  //rfq apis
  fetchVendorListBasedOnRFQType: `${url}/api/method/vms.APIs.req_for_quotation.rfq_for_logistic.vendor_list`,
  CreateImportRFQ: `${url}/api/method/vms.APIs.req_for_quotation.rfq_for_logistic.create_import_logistic_rfq`,
  CreateExportRFQ: `${url}/api/method/vms.APIs.req_for_quotation.rfq_for_logistic.create_export_logistic_rfq`,
  rfqTableData: `${url}/api/method/vms.APIs.req_for_quotation.rfq.rfq_dashboard`,
  fetchPRDropdown: `${url}/api/method/vms.APIs.req_for_quotation.rfq_for_material.pr_number_list`,
  fetchPRItems: `${url}/api/method/vms.APIs.req_for_quotation.rfq_for_material.add_pr_number`,
  CreateMaterialRFQ: `${url}/api/method/vms.APIs.req_for_quotation.rfq_for_material.create_rfq_material`,
  CreateServiceRFQ: `${url}/api/method/vms.APIs.req_for_quotation.rfq_for_service.create_rfq_service`,
  ReviseRFQ: `${url}/api/method/vms.APIs.req_for_quotation.rfq.send_revised_rfq`,
  CountryExportDropdown: `${url}/api/method/vms.APIs.req_for_quotation.rfq.get_countries_with_ports`,
  fetchDestinationPortBasedonShipmentType: `${url}/api/method/vms.APIs.req_for_quotation.rfq.get_ports_by_mode_of_shipment_simple`,
  fetchSerialNumber: `${url}/api/method/vms.APIs.req_for_quotation.rfq.get_next_rfq_serial_number`,
  fetchPortNumber: `${url}/api/method/vms.APIs.master_apis.port_master.get_port_master`,
  fetchCountry: `${url}/api/method/vms.APIs.master_apis.get_country.get_country_master`,

  //Quatataion apis
  SubmitQuatation: `${url}/api/method/vms.APIs.quotation.create_quotation.create_or_update_quotation`,
  getRFQData: `${url}/api/method/vms.APIs.req_for_quotation.rfq.get_full_rfq_data`,
  fetchQuatationVendorList: `${url}/api/method/vms.APIs.quotation.quotation.get_quotations_by_rfq`,
  ApproveQuotation: `${url}/api/method/vms.APIs.quotation.quotation.approve_quotation`,
  quotationTracking: `${url}/api/method/vms.APIs.quotation.create_quotation.get_quotation_details_by_token`,
  NegotiateQuotation: `${url}/api/method/vms.APIs.quotation.quotation.update_final_negotiated_rate`,

  //Public apis
  ProcessToken: `${url}/api/method/vms.purchase.doctype.request_for_quotation.request_for_quotation.process_token`,
  SubmitPublicQuatation: `${url}/api/method/vms.APIs.quotation.create_quotation.create_or_update_quotation_non_onboarded`,
   QuotationDetail:`${url}/api/method/vms.APIs.quotation.quotation.get_quotation_details`,
  // Amend APIs
  AmendAPI: `${url}/api/method/vms.APIs.vendor_onboarding.onboarding_amendment.create_vendor_onboarding_amendment`,
  
  // GRN APIs
  AllGRNdetails: `${url}/api/method/vms.APIs.grn_apis.all_grn_details.get_all_grn_details`,
  SingleGRNdetails: `${url}/api/method/vms.APIs.grn_apis.all_grn_details.get_grn_details_of_grn_number`,
  UserDetails: `${url}/api/method/vms.APIs.authentication_api.get_user_details.get_user_details`,
  AllPRDetails: `${url}/api/method/vms.APIs.grn_apis.all_grn_details.filtering_pr_details`,
  GRNUpdateDetails: `${url}/api/method/vms.APIs.grn_apis.all_grn_details.update_grn_with_data`,

  // getPrintFormatData:`${ url } /api/method / vms.APIs.dashboard_api.po_data.get_po_details`,
  getPrintFormatData: `${url}/api/method/vms.APIs.dashboard_api.po_data.get_po_details_withformat`,
  addGSTTAbleData: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_document_details.update_vendor_onboarding_gst_details`,
  deleteGSTRow: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_document_details.delete_vendor_onboarding_gst_row`,
  gstVendorStateDropdown: `${url}/api/method/vms.APIs.master_apis.state_filter.get_states_for_gst`,
  getPODatainUserConfirmation: `${url}/api/method/vms.APIs.dashboard_api.po_data.get_po_details`,
  senduserconfirmationemail: `${url}/api/method/vms.APIs.user_confirmation.user_confirmation.send_po_user_confirmation`,
  sendaccountsteamemailuserconf: `${url}/api/method/vms.APIs.user_confirmation.user_confirmation.send_payment_release_notification_api`,
  sendvendoremailonuser: `${url}/api/method/vms.APIs.user_confirmation.user_confirmation.send_vendor_delivery_issue_email`,
  POItemsTable: `${url}/api/method/vms.APIs.purchase_api.purchase_order.get_purchase_order_items_by_name`,
  submitPOItems: `${url}/api/method/vms.APIs.purchase_api.purchase_order.update_purchase_team_remarks`,
  POItemsApproval: `${url}/api/method/vms.APIs.purchase_api.purchase_order.update_vendor_approval_status`,

  // ASA Form API:
  getASAFormSubmit: `${url}/api/method/vms.APIs.assessment_apis.asa.get_data_ann_ass_form`,
  asaformSubmit: `${url}/api/method/vms.APIs.assessment_apis.asa.create_annual_ass_form`,
  asagrovernanceformSubmit: `${url}/api/method/vms.APIs.assessment_apis.asa.create_gov_asa_form`,
  asasocialformSubmit: `${url}/api/method/vms.APIs.assessment_apis.asa.create_social_asa_form`,
  asaenvformSubmit: `${url}/api/method/vms.APIs.assessment_apis.asa.create_env_asa_form`,
  asavendorListdashboard: `${url}/api/method/vms.APIs.assessment_apis.asa_dashboard.asa_dashboard`,
  asaonboardedvendorcount: `${url}/api/method/vms.APIs.assessment_apis.asa_dashboard.approved_vendor_count`,
  asapendingVendorcount: `${url}/api/method/vms.APIs.assessment_apis.asa_dashboard.pending_asa_count`,
  asapendingVendorList: `${url}/api/method/vms.APIs.assessment_apis.asa_dashboard.pending_asa_vendor_list`,
  asasendremindermail: `${url}/api/method/vms.APIs.assessment_apis.asa_dashboard.send_asa_reminder_email`,
  asaonboardedvendorlist: `${url}/api/method/vms.APIs.assessment_apis.asa_dashboard.approved_vendor_list`,

  // All Approved Vendors Speicfy Detail API
  allvendorsdetails: `${url}/api/method/vms.APIs.dashboard_api.vendor_brief.get_vendors_with_pagination`,
  allvendorscompanycodedetails: `${url}/api/method/vms.APIs.dashboard_api.vendor_code_brief.get_comp_ven_code`,
  allvendorsspecificdetails: `${url}/api/method/vms.APIs.dashboard_api.vendor_specific_data.get_vendor_complete_ecosystem`,

  // Company Filter API for Purchase Enquiry and Purchase Requisition
  filterpurchasegroup: `${url}/api/method/vms.APIs.purchase_api.purchase_inquiry.filter_purchase_group`,
  filterstoragelocation: `${url}/api/method/vms.APIs.purchase_api.purchase_requisition.filter_store_location`,
  filtercostcenter: `${url}/api/method/vms.APIs.purchase_api.purchase_requisition.filter_cost_center`,
  filterglaccount: `${url}/api/method/vms.APIs.purchase_api.purchase_requisition.filter_gl_account`,
  filtermaterialgroup: `${url}/api/method/vms.APIs.purchase_api.purchase_requisition.filter_material_group_master`,
  filterprofitcenter: `${url}/api/method/vms.APIs.purchase_api.purchase_requisition.filter_profit_center`,
  filtervaluationclass: `${url}/api/method/vms.APIs.purchase_api.purchase_requisition.filter_valuation_class_master`,
  filterMaterialCode: `${url}/api/method/vms.APIs.purchase_api.purchase_requisition.filter_material_master`,
  filterpurchaseorg: `${url}/api/method/vms.APIs.purchase_api.purchase_requisition.filter_purchase_organisation`,
  getPrintFormatDropdown: `${url}/api/method/vms.APIs.master_apis.po_print.get_po_printformat`,
  getStateBasedOnPincode: `${url}/api/method/vms.APIs.master_apis.address_custom.address_filter`,
  getAllPOChangesTable: `${url}/api/method/vms.APIs.purchase_api.po_early_deliver_get.filtering_po_earlydel_details`,
  getPONumberDropdown: `${url}/api/method/vms.APIs.purchase_api.po_early_deliver_get.filtering_po_details`,
  sendPOEmailVendor: `${url}/api/method/vms.APIs.purchase_api.send_po_to_pr.send_po_to_pr`,
  verifyNewVendor: `${url}/api/method/vms.APIs.req_for_quotation.rfq.check_duplicate_vendor`,

  sapApiDashboardDetails: `${url}/api/method/vms.APIs.dashboard_api.dashboard_filters_data.sap_error_vendor_details`,
  sapErrorSendEmail: `${url}/api/method/vms.APIs.sap.send_sap_error_email.send_sap_error_email`,
  dashboardPendingVendorsAccounts: `${url}/api/method/vms.APIs.dashboard_api.dashboard_filters_data.pending_vendor_details_by_accounts`,
  dashboardOnboardedVendorsAccounts: `${url}/api/method/vms.APIs.dashboard_api.dashboard_filters_data.approved_vendor_details_by_accounts`,
  dashboardRejectedVendorsAccounts: `${url}/api/method/vms.APIs.dashboard_api.dashboard_filters_data.rejected_vendor_details_by_accounts`,
  dashboardSapErrorAcounts: `${url}/api/method/vms.APIs.dashboard_api.dashboard_filters_data.sap_error_vendor_details_by_accounts`,
  bankProofByPurchaseTeam: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_payment_details.update_bank_proof_purchase_team`,
  DispatchStateAndPlant: `${url}/api/method/vms.APIs.dispatch.vehicle_details.get_state_and_plant_data`,

  // bankProofByPurchaseTeam:`${url}/api/method/vms.APIs.vendor_onboarding.vendor_payment_details.update_bank_proof_purchase_team`,

  // QA Dashboard APIs
  TotalQMSDocs: `${url}/api/method/vms.APIs.qms_dashboard.qms_dashboard.total_qms_onboarding_details`,
  PendingQMDocs: `${url}/api/method/vms.APIs.qms_dashboard.qms_dashboard.pending_qms_onboarding_details`,
  FullyFilledQMSDocs: `${url}/api/method/vms.APIs.qms_dashboard.qms_dashboard.completed_qms_onboarding_details`,
  DraftQMSDocs: `${url}/api/method/vms.APIs.qms_dashboard.qms_doc_dashboard.draft_qms_details`,
  ApprovedQMSDocs: `${url}/api/method/vms.APIs.qms_dashboard.qms_doc_dashboard.approved_qms_details`,
  RejectedQMSDocs: `${url}/api/method/vms.APIs.qms_dashboard.qms_doc_dashboard.rejected_qms_details`,

  // View Vendor Profile APIs
  getvendorsmerilcompany: `${url}/api/method/vms.APIs.vendors_dashboards_api.vendor_data.get_vendor_multi_company`,
  getvendorsonboardingidandstatus: `${url}/api/method/vms.APIs.vendors_dashboards_api.vendor_data.get_vendor_onb_via_company`,
  submitVehicalDispatchForm: `${url}/api/method/vms.APIs.dispatch.vehicle_details.create_vehicle_details`,
  deleteDispatchVehicalItem: `${url}/api/method/vms.APIs.dispatch.vehicle_details.remove_vehicle_from_dispatch`,

  // Notifications APIs
  notificationlist: `${url}/api/method/vms.APIs.notification_chatroom.get_notification.get_notifications`,
  detailednotification: `${url}/api/method/vms.APIs.notification_chatroom.get_notification.get_notification_detail`,
  markallnotificationread: `${url}/api/method/vms.APIs.notification_chatroom.get_notification.mark_all_notifications_read`,
  purchasingdetailschangeemail: `${url}/api/method/vms.APIs.vendor_onboarding.vendors_doc_changes_req_email.email_to_change_pur_detail`,

  // Delete Uploaded File API Payment Details
  deleteTwoWayBankFile: `${url}/api/method/vms.APIs.vendor_onboarding.vendor_payment_details.delete_bank_proof_attachment`,

  // All VEndors Copy and Extend APIs
  copyexistingvendors: `${url}/api/method/vms.APIs.vendor_onboarding.extend_vendor_code_in_sap.create_vendor_data_from_existing_onboarding`,
  extendexistingvendors: `${url}/api/method/vms.APIs.vendor_onboarding.extend_vendor_code_in_sap.send_vendor_code_extend_mail`,

  // Admin Head Dashboard APIs
  PurchaseTeamFilter: `${url}/api/method/vms.APIs.dashboard_api.dashboard_for_super_head.team_filter_options`,
  PurchaseTeamSAPError: `${url}/api/method/vms.APIs.dashboard_api.dashboard_for_super_head.sap_error_vendor_details_by_purchase`,
  PurchaseTeamRejectedVendors: `${url}/api/method/vms.APIs.dashboard_api.dashboard_for_super_head.rejected_vendor_details_by_purchase`,
  PurchaseTeamApprovedVendors: `${url}/api/method/vms.APIs.dashboard_api.dashboard_for_super_head.approved_vendor_details_by_purchase`,
  PurchaseTeamPendingVendors: `${url}/api/method/vms.APIs.dashboard_api.dashboard_for_super_head.pending_vendor_details_by_purchase`,
  PurchaseTeamPODetailsList: `${url}`,
  PurchaseTeamRFQList: `${url}`,
  AccountsTeamSAPError: `${url}/api/method/vms.APIs.dashboard_api.dashboard_for_super_head.sap_error_vendor_details_by_accounts`,
  AccountsTeamPendingVendors: `${url}/api/method/vms.APIs.dashboard_api.dashboard_for_super_head.pending_vendor_details_by_accounts`,
  AccountsTeamRejectedVendors: `${url}/api/method/vms.APIs.dashboard_api.dashboard_for_super_head.rejected_vendor_details_by_accounts`,
  AccountsTeamApprovedVendors: `${url}/api/method/vms.APIs.dashboard_api.dashboard_for_super_head.approved_vendor_details_by_accounts`,

  addProductInquiryProducts:`${url}/api/method/vms.APIs.purchase_api.purchase_inquiry.update_cart_products`,
  deleteInquiryProductItem:`${url}/api/method/vms.APIs.purchase_api.purchase_inquiry.delete_cart_product`,
  InquiryAddtionalApproval:`${url}/api/method/vms.APIs.purchase_api.purchase_inquiry_approvals.send_purchase_enquiry_approval_mail`,
  submitPrInquiry:`${url}/api/method/vms.APIs.purchase_api.purchase_inquiry.submit_purchase_inquiry`,

    //gate Entry
  sendQRData:`${url}/api/method/vms.APIs.dispatch.dispatch.get_dispatch_data`,
  sendGateEntry:`${url}/api/method/vms.APIs.dispatch.gate_entry.create_gate_entry`,
  fetchGateEntry:`${url}/api/method/vms.APIs.dispatch.get_gate_entry.gate_entry_get`,
  inwardLocationDropdown:`${url}/api/method/vms.APIs.dispatch.gate_entry.get_inward_location`,
  handoverPersonDropdown:`${url}/api/method/vms.APIs.dispatch.gate_entry.get_handover_person`,
  handover_submit:`${url}/api/method/vms.APIs.dispatch.gate_entry.handover_gate_entry`,
  GateEntryDashboardCardCount:`${url}/api/method/vms.APIs.dispatch.get_gate_entry.get_gate_entry_statistics`,
  GateEntryTableData:`${url}/api/method/vms.APIs.dispatch.get_gate_entry.gate_entry_get`
}

export default API_END_POINTS;
