export const tableData = [
  {
    srno: "INV001",
    refno: "VMS/8000/0069",
    vendor_name: "Jhon Doe",
    company_name: "XYZ Corp",
    purchase_team: "Pending by Gireesh Patel",
    purchase_head: "Pending by Unknown",
    accounts_team: "Accounts Team",
    view_detail: "",
    qms_form: "N/A",
    status: "pending",
  },
  {
    srno: "INV002",
    refno: "VMS/8000/0070",
    vendor_name: "Jane Smith",
    company_name: "ABC Industries",
    purchase_team: "Pending by Arun Sharma",
    purchase_head: "Pending by Anita Verma",
    accounts_team: "Accounts Team",
    view_detail: "",
    qms_form: "N/A",
    status: "approved",
  },
  {
    srno: "INV003",
    refno: "VMS/8000/0071",
    vendor_name: "Michael Johnson",
    company_name: "Global Tech",
    purchase_team: "Pending by Priya Reddy",
    purchase_head: "Pending by Unknown",
    accounts_team: "Accounts Team",
    view_detail: "",
    qms_form: "N/A",
    status: "rejected",
  },
  {
    srno: "INV004",
    refno: "VMS/8000/0072",
    vendor_name: "Sarah Lee",
    company_name: "Tech Solutions",
    purchase_team: "Pending by Gireesh Patel",
    purchase_head: "Pending by Rajesh Singh",
    accounts_team: "Accounts Team",
    view_detail: "",
    qms_form: "N/A",
    status: "approved",
  },
  {
    srno: "INV005",
    refno: "VMS/8000/0073",
    vendor_name: "Chris Evans",
    company_name: "Future Innovations",
    purchase_team: "Pending by Meera Gupta",
    purchase_head: "Pending by Unknown",
    accounts_team: "Accounts Team",
    view_detail: "",
    qms_form: "N/A",
    status: "pending",
  },
  {
    srno: "INV006",
    refno: "VMS/8000/0074",
    vendor_name: "Emma Watson",
    company_name: "Creative Minds",
    purchase_team: "Pending by Rajesh Singh",
    purchase_head: "Pending by Anita Verma",
    accounts_team: "Accounts Team",
    view_detail: "",
    qms_form: "N/A",
    status: "approved",
  },
  {
    srno: "INV007",
    refno: "VMS/8000/0075",
    vendor_name: "Tom Hanks",
    company_name: "Innovation Hub",
    purchase_team: "Pending by Arun Sharma",
    purchase_head: "Pending by Unknown",
    accounts_team: "Accounts Team",
    view_detail: "",
    qms_form: "N/A",
    status: "rejected",
  },
  {
    srno: "INV008",
    refno: "VMS/8000/0076",
    vendor_name: "Robert Downey Jr.",
    company_name: "Elite Enterprises",
    purchase_team: "Pending by Priya Reddy",
    purchase_head: "Pending by Rajesh Singh",
    accounts_team: "Accounts Team",
    view_detail: "",
    qms_form: "N/A",
    status: "approved",
  },
];
