export const NavbarConstant:Record<string,string> = {
    "/vendor-registration":"Vendor Registration",
    "/dashboard":"Dashboard",
    "/pr-request":"Create Purchase Requisition (PR)",
    "/pr-inquiry":"Purchase Enquiry",
    "/view-pr-inquiry":"View Purchase Enquiry",
    "/dispatch":"Dispatch",
    "/view-grn":"Good Receipts Note (GRN)",
    "/view-grn-details":"Good Receipts Note (GRN)",
    "/qms-form-details":"QMS Form",
    "/view-purchase-requisition":"Purchase Requisition (PR)",
    "/view-po-conf":"User Confirmation",
    "/asa-form": "Annual Supplier Assessment Questionnarie",
    "/view-vendor-asa": "Annual supplier Assessment (ASA)",
    "/vendor-dashboard": "Dashboard",
    "/view-asa-form": "Annual Supplier Assessment (ASA)",
    "/view-onboarding-details": "Onboarding details",
    "/create-rfq": "Raise Request for Quotations (RFQ)",
    "/view-po": "View Purchase Order (PO)",
    "/view-dispatch": "Dispatch Details",
    "/all-vendors": "List of Approved Vendors",
    "/qa-dashboard": "Dashboard",
    "/view-profile": "Vendor Profile",
    "/view-rfq": "Request for Quotations (RFQ)",
    "/view-quotation": "Quotation",
    "/view-all-po-changes": "Changed PO Details",
    "/head-dashboard": "Dashboard",
    "/view-shipment-status": "Shipment Status (DSR)",
    "/new-shipment-status": "New Shipment Status (DSR)",
    "/service-bill-dashboard": "Service Bill(SB) Dashboard",
    "/new-service-bill": "New Service Bill (SB)",
    // "/view-all-po-changes": "Changed PO Details",
    "/gate-entry":"Gate Entry",
    "/view-gate-entry":"View Gate Entry",
    "/gate-entry-dashboard":"Gate-entry Dashboard",
    "/shipment-status-dashboard": "Shipment Status(DSR) Dashboard",
    "/view-vendor-po": "Purchase Order (PO)",
}