import { iteminterface } from "../components/molecules/ViewRFQ/RFQDatas";

export const RFQlogicIm : iteminterface[] = [
  { label: "Sr No. :", key: "sr_no" },
  { label: "Shipment Type :", key: "shipment_type" },
  { label: "Package Type :", key: "package_type" },
  { label: "RFQ Type :", key: "rfq_type" },
  { label: "Destination Port :", key: "destination_port" },
  { label: "Vol Weight(KG) :", key: "vol_weight" },
  { label: "Service Type :", key: "service_provider" },
  { label: "Country :", key: "country" },
  { label: "Actual Weight(KG) :", key: "actual_weight" },
  { label: "Company Name :", key: "company_name_logistic" },
  { label: "Port Code :", key: "port_code" },
  { label: "Invoice Date :", key: "invoice_date" },
  { label: "RFQ Date :", key: "rfq_date_logistic" },
  { label: "Port of Loading :", key: "port_of_loading" },
  { label: "Invoice No :", key: "invoice_no" },
  { label: "RFQ CutOff :", key: "rfq_cutoff_date_logistic" },
  { label: "Inco Terms :", key: "inco_terms" },
  { label: "Invoice Value :", key: "invoice_value" },
  { label: "Mode of Shipment :", key: "mode_of_shipment" },
  { label: "Product Category :", key: "product_category" },
  { label: "Expected Date of Arrival :", key: "expected_date_of_arrival" },
  { label: "Shipper Name :", key: "shipper_name" },
  { label: "No.Of Pkg Units :", key: "no_of_pkg_units" },
];

export const RFQlogicEx: iteminterface[] = [{ label: "Sr No. :", key: "sr_no" },
  { label: "Shipment Date :", key: "shipment_date" },
  { label: "Package Type :", key: "package_type" },
  { label: "RFQ Type :", key: "rfq_type" },
  { label: "Destination Port :", key: "destination_port" },
  { label: "Vol Weight(KG) :", key: "vol_weight" },
  { label: "Service Type :", key: "service_provider" },
  { label: "Country :", key: "country" },
  { label: "Actual Weight(KG) :", key: "actual_weight" },
  { label: "Company Name :", key: "company_name_logistic" },
  { label: "Port Code :", key: "port_code" },
  { label: "Invoice Date :", key: "invoice_date" },
  { label: "RFQ Date :", key: "rfq_date_logistic" },
  { label: "Port of Loading :", key: "port_of_loading" },
  { label: "Invoice No :", key: "invoice_no" },
  { label: "RFQ CutOff :", key: "rfq_cutoff_date_logistic" },
  { label: "Inco Terms :", key: "inco_terms" },
  { label: "No.Of Pkg Units :", key: "no_of_pkg_units" },
  { label: "Mode of Shipment :", key: "mode_of_shipment" },
  { label: "Product Category :", key: "product_category" },
  { label: "Ship to Address :", key: "ship_to_address" },
  { label: "Consignee Name :", key: "consignee_name" },
];

export const RFQmaterial: iteminterface[] = [{ label: "RFQ Type :", key: "rfq_type" },
  { label: "Company Name :", key: "company_name" },
  { label: "Requestor Name :", key: "requestor_name" },
  { label: "RFQ Date :", key: "rfq_date" },
  { label: "Collection No. :", key: "collection_number" },
  { label: "1st Reminder :", key: "first_remainder" },
  { label: "Quotation Deadline :", key: "quotation_deadline" },
  { label: "Select Currency :", key: "currency" },
  { label: "2nd Reminder :", key: "second_remainder" },
  { label: "Purchasing Organization :", key: "purchase_organization" },
  { label: "Purchase Group :", key: "purchase_group" },
  { label: "3rd Reminder :", key: "third_remainder" }
];

export const RFQservices: iteminterface[] = [{ label: "RFQ Type :", key: "rfq_type" },
  { label: "Company Name :", key: "company_name" },
  { label: "Purchasing Organization :", key: "purchase_organization" },
  { label: "RFQ Quantity :", key: "rfq_quantity" },
  { label: "Purchase Group :", key: "purchase_group" },
  { label: "Collection No. :", key: "collection_number" },
  { label: "Quotation Deadline :", key: "quotation_deadline" },
  { label: "Storage Location :", key: "storage_location" },
  { label: "Bidding Person :", key: "bidding_person" },
  { label: "Quantity Unit :", key: "quantity_unit" },
  { label: "Short Text :", key: "short_text" },
  { label: "1st Reminder :", key: "first_reminder" },
  { label: "Plant Code :", key: "plant_code" },
  { label: "Service Location :", key: "service_location" },
  { label: "2nd Reminder :", key: "second_reminder" },
  { label: "Service Category :", key: "service_category" },
  { label: "Delivery Date :", key: "delivery_date" },
  { label: "3rd Reminder :", key: "third_reminder" },
  { label: "Material Code :", key: "material_code" },
  { label: "Select Currency :", key: "currency" },
  { label: "Enter estimated Price :", key: "estimated_price" }  
];
