"use client";

import { useEffect, useMemo, useState, useCallback } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import requestWrapper from "@/src/services/apiCall";
import API_END_POINTS from "@/src/services/apiEndPoints";
import { EDIT_ROLES } from "@/src/constants/materialRoles";
import { getMaterialTabs } from "@/src/constants/materialTabs";

export const useMaterialOnboardingForm = ({
  form,
  MaterialOnboardingDetails,
  MaterialDetails,
  EmployeeDetailsJSON,
  ProfitCenter = [],
  role,
  setLineItemFiles
}: any) => {

  const router = useRouter();
  const searchParams = useSearchParams();
  const name = searchParams.get("name");

  const [activeTab, setActiveTab] = useState("basic-data");
  const [fileSelected, setFileSelected] = useState(false);
  const [fileName, setFileName] = useState("");
  const [showSAPModal, setShowSAPModal] = useState(false);
  const [showRemarkDialog, setShowRemarkDialog] = useState(false);
  const [materialCompanyCode, setMaterialCompanyCode] = useState("");
  const [shouldShowAllFields, setShouldShowAllFields] = useState(false);
  const [isMatchedMaterial, setIsMatchedMaterial] = useState(false);

  const approvalStatus = MaterialOnboardingDetails?.approval_status?.trim() ?? "";
  const isPendingByCP = approvalStatus === "Pending by CP";
  const isCodeGeneratedBySAP = approvalStatus === "Code Generated by SAP";

  const revisedFlag = MaterialDetails?.material_request_item?.is_revised_code_new;
  const isRevisedNewCode = revisedFlag === 1 || revisedFlag === true;

  const finalShouldShowAllFields =
    isRevisedNewCode || (!isPendingByCP && shouldShowAllFields);

  const materialType = MaterialOnboardingDetails?.material_type_name;
  const isZCAPMaterial = materialType === "ZCAP";

  const tabs = useMemo(
    () => getMaterialTabs(role, finalShouldShowAllFields, isZCAPMaterial),
    [role, finalShouldShowAllFields, isZCAPMaterial]
  );

  const availableTabs = tabs.map((t: any) => t.id);

  useEffect(() => {
    const currentDate = new Date().toISOString().split("T")[0];
    if (!form.getValues("request_date")) {
      form.setValue("request_date", currentDate);
    }
  }, [form]);

  useEffect(() => {
    if (MaterialOnboardingDetails?.approval_status === "Code Generated by SAP") {
      setShowSAPModal(true);
    }
  }, [MaterialOnboardingDetails]);

  useEffect(() => {
    if (!availableTabs.includes(activeTab)) {
      setActiveTab(availableTabs[0]);
    }
  }, [availableTabs, activeTab]);

  useEffect(() => {
    const revisedFlag = MaterialDetails?.material_request_item?.is_revised_code_new;
    setIsMatchedMaterial(!(revisedFlag === 1 || revisedFlag === true));
  }, [MaterialDetails]);

  const filteredProfit = useMemo(() => {

    if (!EmployeeDetailsJSON?.company || !ProfitCenter?.length) return [];

    const employeeCompanyCodes =
      EmployeeDetailsJSON.company.map((c: any) => String(c.company_code));

    return ProfitCenter.filter((pc: any) =>
      employeeCompanyCodes.includes(String(pc.company_code))
    );

  }, [EmployeeDetailsJSON, ProfitCenter]);

  const handleNextTab = () => {
    const idx = availableTabs.indexOf(activeTab);
    if (idx < availableTabs.length - 1) {
      setActiveTab(availableTabs[idx + 1]);
    }
  };

  const handlePrevTab = () => {
    const idx = availableTabs.indexOf(activeTab);
    if (idx > 0) {
      setActiveTab(availableTabs[idx - 1]);
    }
  };

  const handleImageChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>, key: string) => {

      const file = e.target.files?.[0];
      if (!file || !setLineItemFiles) return;

      const fileURL = URL.createObjectURL(file);

      setLineItemFiles((prev: any) => ({
        ...prev,
        [key]: { file, fileURL }
      }));

      setFileSelected(true);
      setFileName(file.name);

    },
    [setLineItemFiles]
  );

  const handleRemoveFile = useCallback((inputId: string) => {

    if (!setLineItemFiles) return;

    setLineItemFiles((prev: any) => {
      const updated = { ...prev };
      delete updated["material_information"];
      return updated;
    });

    const input = document.getElementById(inputId) as HTMLInputElement;
    if (input) input.value = "";

    setFileSelected(false);
    setFileName("");

  }, [setLineItemFiles]);

  const handleSubmit = async (values: any) => {

    const payload = {
      requestor_ref_no: name,
      ...values
    };

    try {

      const response: any = await requestWrapper({
        url: API_END_POINTS.creatematerialonboarding,
        method: "POST",
        data: payload
      });

      if (response?.status === 200) {
        alert("Material details sent to SAP successfully");
      }

    } catch (error) {
      console.error(error);
      alert("Something went wrong");
    }

  };

  const onCancel = () => router.push("/view-material-code-request");

  return {
    activeTab,
    setActiveTab,
    tabs,
    availableTabs,
    fileSelected,
    fileName,
    setFileName,
    showSAPModal,
    setShowSAPModal,
    showRemarkDialog,
    setShowRemarkDialog,
    materialCompanyCode,
    setMaterialCompanyCode,
    filteredProfit,
    isZCAPMaterial,
    isMatchedMaterial,
    finalShouldShowAllFields,
    handleNextTab,
    handlePrevTab,
    handleImageChange,
    handleRemoveFile,
    handleSubmit,
    onCancel,
    isCodeGeneratedBySAP
  };

};