import React, { useState, useEffect } from "react";
import { UseFormReturn } from "react-hook-form";
import { Button } from "@/components/ui/button";
import RequestorInformation from "@/src/components/molecules/material-onboarding/requestor-information";
import MaterialInformation from "@/src/components/molecules/material-onboarding/material-information";
import { MaterialRegistrationFormData } from "@/src/types/MaterialCodeRequestFormTypes";
import AlertBox from "../../common/vendor-onboarding-alertbox";
import { EmployeeDetail, Company, UOMMaster, MaterialCategory } from "@/src/types/MaterialCodeRequestFormTypes";
import SAPMaterialModal from "@/src/components/molecules/material-onboarding-modal/SAPMaterialModal";


interface MastersData {
    companyMaster: Company[];
    uomMaster: UOMMaster[];
    materialCategoryMaster: MaterialCategory[];
}

interface MaterialOnboardingFormProps {
    form: UseFormReturn<MaterialRegistrationFormData>;
    onCancel: (e: React.MouseEvent<HTMLButtonElement>) => void;
    onSubmit: (data: MaterialRegistrationFormData) => void;
    onUpdate: (e: React.MouseEvent<HTMLButtonElement>) => void;
    onError: (errors: any) => void;
    masters: MastersData;
    showAlert: any;
    isLoading: any;
    isButtonDisabled: any;
    materialRequestList: MaterialRegistrationFormData;
    EmployeeDetailsJSON: EmployeeDetail | null;
}

const MaterialOnboardingForm: React.FC<MaterialOnboardingFormProps> = ({ form, onCancel, onSubmit, onUpdate, onError, materialRequestList, masters, isLoading, showAlert, EmployeeDetailsJSON }) => {
    console.log("Material Request List in Form--->", EmployeeDetailsJSON);
    const [showSAPModal, setShowSAPModal] = useState(false);
    const materialType = materialRequestList?.material_type_name;
    const isZCAPMaterial = materialType === "ZCAP";

    useEffect(() => {
        if (materialRequestList?.approval_status === "Code Generated by SAP") {
            setShowSAPModal(true);
        }
    }, [materialRequestList?.approval_status]);

    const basicMasters = {
        companyMaster: masters.companyMaster,
        materialCategoryMaster: masters.materialCategoryMaster,
        uomMaster: masters.uomMaster,
    };

    return (
        <form onSubmit={form.handleSubmit(onSubmit, onError)} className="bg-transparent space-y-4 border-none shadow-none">
            <div className="space-y-2">

                {/* === SAP MODAL === */}
                <SAPMaterialModal
                    isOpen={showSAPModal}
                    onClose={() => setShowSAPModal(false)}
                    materialCode={materialRequestList?.material_code_revised || ""}
                    materialDescription={materialRequestList?.material_name_description || ""}
                    isZCAPMaterial={isZCAPMaterial}
                />

                <RequestorInformation
                    form={form}
                    MaterialOnboarding={materialRequestList}
                    EmployeeDetails={EmployeeDetailsJSON || {} as EmployeeDetail}
                />

                <MaterialInformation
                    form={form}
                    basicMasters={basicMasters}
                    MaterialOnboarding={materialRequestList}
                    EmployeeDetails={EmployeeDetailsJSON || {} as EmployeeDetail}
                />
            </div>

            <div className="mt-6 pb-3">
                <div className="flex justify-end space-x-6 items-center">
                    <Button
                        variant="backbtn"
                        size="backbtnsize"
                        className="py-2.5 bg-white"
                        onClick={onCancel}
                    >
                        Cancel
                    </Button>

                    {(materialRequestList?.approval_status === "" ||
                        materialRequestList?.approval_status === undefined) && (
                            <Button
                                variant="nextbtn"
                                size="nextbtnsize"
                                type="submit"
                                className="py-2.5"
                            >
                                {isLoading ? "Processing..." : "Submit"}
                            </Button>
                        )}

                    {materialRequestList?.approval_status === "Re-Opened by CP" && (
                        <Button
                            variant="nextbtn"
                            size="nextbtnsize"
                            type="button"
                            className="py-2.5"
                            onClick={onUpdate}
                        >
                            {isLoading ? "Processing..." : "Update"}
                        </Button>
                    )}

                    {showAlert && (
                        <AlertBox
                            content={"Your Details have been submitted successfully!"}
                            submit={showAlert}
                            url="new-material-code-request-table"
                        />
                    )}
                </div>
            </div>
        </form>
    );
};

export default MaterialOnboardingForm;