"use client";

import React, { useState, useEffect } from "react";
import MaterialRequestForm from "./material-request-form";
import { MaterialCode } from "@/src/types/PurchaseRequestType";
import { UseFormReturn } from "react-hook-form";
import { MaterialRegistrationFormData } from "@/src/types/MaterialCodeRequestFormTypes";
import API_END_POINTS from '@/src/services/apiEndPoints'
import { AxiosResponse } from 'axios'
import requestWrapper from '@/src/services/apiCall';
import { EmployeeDetail } from "@/src/types/MaterialCodeRequestFormTypes";

interface MaterialInformationProps {
  form: UseFormReturn<any>;
  basicMasters: {
    companyMaster: any[];
    materialCategoryMaster: any[];
    uomMaster: any[];
  };
  MaterialOnboarding?: MaterialRegistrationFormData;
  EmployeeDetails: EmployeeDetail | null;

}

export default function MaterialInformation({ form, basicMasters, MaterialOnboarding, EmployeeDetails }: MaterialInformationProps) {

  const [searchResults, setSearchResults] = useState<any[]>([]);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [materialSelectedFromList, setMaterialSelectedFromList] = useState(false);
  const [materialCodeAutoFetched, setMaterialCodeAutoFetched] = useState(false);
  const [selectedMaterialType, setSelectedMaterialType] = useState("");
  const [AllMaterialCodes, setAllMaterialCodes] = useState<MaterialCode[]>([]);
  const [materialCodeStatus, setMaterialCodeStatus] = useState<"idle" | "checking" | "exists" | "available">("idle");
  const [selectedCodeLogic, setSelectedCodeLogic] = useState<string>("");
  const [latestCodeSuggestions, setLatestCodeSuggestions] = useState<MaterialCode[]>([]);

  const fetchMaterialCodeData = async (query?: string): Promise<MaterialCode[]> => {
    try {
      const company = form.getValues("material_company_code");
      const materialtype = form.getValues("material_type");

      if (!company || !materialtype) {
        setAllMaterialCodes([]);
        return [];
      }

      const filters = {
        company,
        material_type: materialtype,
      };

      let url =
        `${API_END_POINTS.MaterialCodeSearchApi}?filters=${encodeURIComponent(
          JSON.stringify(filters)
        )}`;

      if (query) {
        url += `&search_term=${encodeURIComponent(query)}`;
      }

      const response: AxiosResponse = await requestWrapper({
        url,
        method: "GET",
      });

      if (response?.status === 200) {
        const data = response.data?.message?.data || [];
        console.log("Fetched material codes:", data);
        setAllMaterialCodes(data);
        return data;
      }
    } catch (error) {
      console.error("Error fetching material code data:", error);
    }

    return [];
  };

  const checkMaterialCodeExists = async (code: string) => {
    if (!code) return;

    const approvalStatus = MaterialOnboarding?.approval_status?.trim().toLowerCase();
    const isFinalStatus = approvalStatus === "code generated by sap" || approvalStatus === "use existing code";

    if (isFinalStatus || MaterialOnboarding?.material_code_revised === code) {
      setMaterialCodeStatus("available");
      form.clearErrors("material_code_revised");
      return;
    }

    try {
      setMaterialCodeStatus("checking");

      const company = form.getValues("material_company_code");
      const materialtype = form.getValues("material_type");

      if (!company || !materialtype) {
        setMaterialCodeStatus("idle");
        return;
      }

      const url =
        `${API_END_POINTS.MaterialCodeSearchApi}` +
        `?filters=${encodeURIComponent(
          JSON.stringify({
            company,
            material_type: materialtype,
          })
        )}&search_term=${encodeURIComponent(code)}`;

      const response: AxiosResponse = await requestWrapper({
        url,
        method: "GET",
      });

      const data = response?.data?.message?.data || [];
      console.log("Material code check response:", data);

      if (data.length > 0) {
        setMaterialCodeStatus("exists");
        form.setError("material_code_revised", {
          type: "manual",
          message: "Material Code already exists",
        });
      } else {
        setMaterialCodeStatus("available");
        form.clearErrors("material_code_revised");
      }
    } catch (err) {
      console.error("Material code validation failed", err);
      setMaterialCodeStatus("idle");
    }
  };

  const fetchLatestCode = async () => {
    if (!selectedCodeLogic) return;

    const company = form.getValues("material_company_code");
    if (!company) return;

    try {
        const res = await requestWrapper({
          method: "GET",
          url: `${API_END_POINTS.getLatestMaterialCode}?prefix=${selectedCodeLogic}&company=${company}`,
        });
    
        if (res?.data?.message && Object.keys(res.data.message).length > 0) {
          setLatestCodeSuggestions([res.data.message]);
        } else {
          setLatestCodeSuggestions([{ material_code: "No existing code found for this logic" } as any]);
        }
    } catch (e) {
        console.error("fetchLatestCode API Failed", e);
    }
  };

  useEffect(() => {
    fetchLatestCode();
  }, [selectedCodeLogic]);

  useEffect(() => {
    const code = form.watch("material_code_revised");

    if (!code || code.endsWith("-")) {
      setMaterialCodeStatus("idle");
      return;
    }

    const approvalStatus = MaterialOnboarding?.approval_status?.trim().toLowerCase();
    const isFinalStatus =
      approvalStatus === "code generated by sap" ||
      approvalStatus === "use existing code";

    if (isFinalStatus) {
      setMaterialCodeStatus("available");
      form.clearErrors("material_code_revised");
      return;
    }

    const timer = setTimeout(() => {
      checkMaterialCodeExists(code);
    }, 600);

    return () => clearTimeout(timer);
  }, [
    form.watch("material_code_revised"),
    form.watch("material_company_code"),
    form.watch("material_type"),
    MaterialOnboarding?.approval_status,
  ]);

  useEffect(() => {
    const subscription = form.watch(async (value, { name }) => {
      if (
        name === "material_company_code" ||
        name === "material_type"
      ) {
        const company = form.getValues("material_company_code");
        const materialtype = form.getValues("material_type");

        if (company && materialtype) {
          await fetchMaterialCodeData();
        } else {
          setAllMaterialCodes([]);
        }
      }
    });

    return () => subscription.unsubscribe();
  }, [form]);

  const [searchTimeout, setSearchTimeout] = useState<NodeJS.Timeout | null>(null);

  const handleMaterialSearch = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const rawVal = e.target.value;
    const val = rawVal.trim();

    form.setValue("material_name_description", rawVal);

    if (searchTimeout) clearTimeout(searchTimeout);

    if (val.length > 2) {
      const timeout = setTimeout(async () => {
        const results = await fetchMaterialCodeData(val);

        const mappedResults = results.map((item) => ({
          material_name_description: item.material_description,
          material_code_revised: item.name,
          material_type: item.material_type,
        }));

        setSearchResults(mappedResults);
        setShowSuggestions(true);
      }, 400);

      setSearchTimeout(timeout);
    } else {
      setSearchResults([]);
      setShowSuggestions(false);
    }

    setMaterialSelectedFromList(false);
    setMaterialCodeAutoFetched(false);
  };


  const handleMaterialSelect = (item: any) => {
    form.setValue("material_name_description", item.material_name_description);
    form.setValue("material_code_revised", item.material_code_revised);
    form.setValue("material_type", item.material_type);
    setMaterialSelectedFromList(true);
    setMaterialCodeAutoFetched(true);
    setShowSuggestions(false);
  };

  return (
    <div>
      <MaterialRequestForm
        form={form}
        masters={basicMasters}
        MaterialOnboardingDetails={MaterialOnboarding}
        handleMaterialSearch={handleMaterialSearch}
        handleMaterialSelect={handleMaterialSelect}
        searchResults={searchResults}
        showSuggestions={showSuggestions}
        setShowSuggestions={setShowSuggestions}
        materialSelectedFromList={materialSelectedFromList}
        setMaterialSelectedFromList={setMaterialSelectedFromList}
        materialCodeAutoFetched={materialCodeAutoFetched}
        setMaterialCodeAutoFetched={setMaterialCodeAutoFetched}
        setSelectedMaterialType={setSelectedMaterialType}
        materialCodeStatus={materialCodeStatus}
        selectedCodeLogic={selectedCodeLogic}
        setSelectedCodeLogic={setSelectedCodeLogic}
        latestCodeSuggestions={latestCodeSuggestions}
        EmployeeDetails={EmployeeDetails}
      />
    </div>
  );
}
