"use client";

import React, { useEffect, useState } from "react";
import { UseFormReturn } from "react-hook-form";
import { Button } from "@/components/ui/button";
import { useRouter } from "next/navigation";
import { Form } from "@/components/ui/form";
import { Save } from "lucide-react";
import Alertbox from "@/src/components/common/vendor-onboarding-alertbox";
import { useAuth } from "@/src/context/AuthContext";

import MaterialInformation from "@/src/components/molecules/material-onboarding-details/material-information";
import MaterialSpecifications from "@/src/components/molecules/material-onboarding-details/material-specifications";
import MaterialOnboardingApproval from "@/src/components/molecules/material-onboarding-details/material-approval";
import MaterialPurchasingData from "@/src/components/molecules/material-onboarding-details/material-purchasing-data";
import RequesterDetails from "@/src/components/molecules/material-onboarding-details/requester-details";
import MaterialComment from "@/src/components/molecules/material-onboarding-details/material-remarks-field";
import MaterialMRPData from "@/src/components/molecules/material-onboarding-details/material-mrp-data";
import MaterialQAQCData from "@/src/components/molecules/material-onboarding-details/material-qa-qc-data";
import MaterialOtherData from "@/src/components/molecules/material-onboarding-details/material-other-data";
import SAPMaterialModal from "@/src/components/molecules/material-onboarding-modal/SAPMaterialModal";
import RevertRemarkModal from "@/src/components/molecules/material-onboarding-modal/revert-remark-field";

interface FileRecord {
  file: File;
  fileURL: string;
}

interface DropdownOption {
  company_code?: string;
  [key: string]: any;
}

interface MaterialOnboardingFormProps {
  form: UseFormReturn<any>;
  onSubmit: (e: React.FormEvent<HTMLFormElement>) => void;
  isLoading?: boolean;
  showAlert?: boolean;
  showcompletealert?: boolean;
  showRevertAlert?: boolean;
  companyName?: { data: any[] };
  plantcode?: { data: any[] };
  designationname?: string;
  UserDetails?: any;
  EmployeeDetails?: any;
  DivisionDetails?: any;
  IndustryDetails?: any;
  UnitOfMeasure?: any;
  MRPType?: any;
  ValuationClass?: any;
  ProcurementType?: any;
  ValuationCategory?: any;
  MaterialGroup?: any;
  MaterialOnboardingDetails?: any;
  lineItemFiles?: Record<string, FileRecord>;
  setLineItemFiles?: React.Dispatch<React.SetStateAction<Record<string, FileRecord>>>;
  setHsnStatus?: (val: boolean) => void;
  hsnStatus?: boolean;
  companyInfo?: any;
  ProfitCenter?: DropdownOption[];
  PriceControl?: any;
  AvailabilityCheck?: any;
  MaterialType?: any;
  MRPController?: any;
  StorageLocation?: any;
  ClassType?: any;
  PurchaseGroup?: any;
  SerialProfile?: any;
  InspectionType?: any;
  LotSize?: any;
  MaterialDetails?: any;
  materialCompanyCode?: string;
  setMaterialCompanyCode?: (code: string) => void;
  MaterialCode?: any;
  MaterialCategory?: any;
  AllMaterialType?: any;
  SMK?: any;
  ExpirationDate?: any;
  doc_name?: string;
  sendEmailToUser?: (doc: string) => Promise<void>;
  sendRevertEmail?: (doc: string, remark: string) => Promise<void>;
  onCloseCallback?: (doc: string) => void;
  saveAsDraft?: () => void;
  AllMaterialCodes?: any;
}

const MaterialOnboardingForm: React.FC<MaterialOnboardingFormProps> = (props) => {
  const {
    form,
    onSubmit,
    isLoading,
    MaterialOnboardingDetails,
    companyInfo,
    ProfitCenter = [],
    MaterialGroup,
    MaterialCode,
    setLineItemFiles,
    lineItemFiles,
    sendRevertEmail,
    doc_name,
    saveAsDraft,
    onCloseCallback,
    showAlert,
    showcompletealert,
    showRevertAlert,
  } = props;

  const router = useRouter();

  const [fileSelected, setFileSelected] = useState(false);
  const [fileName, setFileName] = useState("");
  const [filteredProfit, setFilteredProfit] = useState<DropdownOption[]>([]);
  const [showSAPModal, setShowSAPModal] = useState(false);
  const [isMaterialCodeEdited, setIsMaterialCodeEdited] = useState(false);
  const [shouldShowAllFields, setShouldShowAllFields] = useState(false);
  const [isMatchedMaterial, setIsMatchedMaterial] = useState(false);
  const [showRemarkDialog, setShowRemarkDialog] = useState(false);
  const { designation } = useAuth();
  const role = designation || ""; 

  // ✅ set default request date
  useEffect(() => {
    const currentDate = new Date().toISOString().split("T")[0];
    if (!form.getValues("request_date")) {
      form.setValue("request_date", currentDate);
    }
  }, [form]);

  // ✅ auto-show SAP modal
  useEffect(() => {
    if (MaterialOnboardingDetails?.approval_status === "Code Generated by SAP") {
      setShowSAPModal(true);
    }
  }, [MaterialOnboardingDetails]);

  // ✅ filter Profit Center by company code
  useEffect(() => {
    const employeeCompanyCode = String(companyInfo?.company_code || "");
    const filtered = ProfitCenter.filter(
      (group) => String(group.company_code) === employeeCompanyCode
    );
    setFilteredProfit(filtered);
  }, [MaterialGroup, companyInfo, ProfitCenter]);

  // ✅ cancel navigation
  const onCancel = (e: React.MouseEvent) => {
    e.preventDefault();
    router.push("/material-onboarding-table");
    window.location.reload();
  };

  // ✅ file handling
  const handleLabelClick = (inputId: string) => {
    document.getElementById(inputId)?.click();
  };

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>, key: string) => {
    const file = e.target.files?.[0];
    if (file && setLineItemFiles) {
      const fileURL = URL.createObjectURL(file);
      setLineItemFiles((prev) => ({
        ...prev,
        [key]: { file, fileURL },
      }));
      setFileSelected(true);
      setFileName(file.name);
    }
  };

  const handleRemoveFile = (inputId: string, clearFileNameFn: (v: string) => void) => {
    if (!setLineItemFiles) return;
    setLineItemFiles((prev) => {
      const updated = { ...prev };
      delete updated["material_information"];
      return updated;
    });
    clearFileNameFn("");
    setFileSelected(false);
    const input = document.getElementById(inputId) as HTMLInputElement;
    if (input) input.value = "";
  };

  // ✅ dynamic button label
  const getButtonLabel = (role: string, approvalStatus?: string): string => {
    if (["CP", "Store"].includes(role)) {
      if (approvalStatus === "Pending by CP" || approvalStatus === "Re-Opened by CP")
        return "Send to SAP";
      if (approvalStatus === "Sent to SAP") return "Update";
    }
    if (role === "SAP") return "Close";
    return "Submit";
  };

  // ✅ approval handling
  const handleApprovalStatus = async () => {
    if (role === "SAP") {
      form.setValue("approval_status", "Code Generated by SAP");
    } else if (
      ["CP", "Store"].includes(role) &&
      MaterialOnboardingDetails?.approval_status === "Sent to SAP"
    ) {
      form.setValue("approval_status", "Updated By CP");
    } else if (
      ["CP", "Store"].includes(role) &&
      MaterialOnboardingDetails?.approval_status === "Pending by SAP"
    ) {
      form.setValue("approval_status", "Sent to SAP");
    }
  };

  // ✅ rejection handler
  const handleRejectStatus = (remark: string) => {
    if (["CP", "Store"].includes(role)) {
      form.setValue("approval_status", "Re-Opened by CP");
      form.setValue("remark_by_cp", remark);
    }
  };

  const approvalStatus = MaterialOnboardingDetails?.approval_status;
  const isSAPLockedStatus = [
    "Sent to SAP",
    "Code Generated by SAP",
    "Pending by CP",
    "Updated by CP",
    "Re-Opened by CP",
  ].includes(approvalStatus);

  const materialType =
    MaterialOnboardingDetails?.material_request?.[0]?.material_type_name;
  const isZCAPMaterial = materialType === "ZCAP";

  return (
    <Form {...form}>
      <form onSubmit={onSubmit}>
        <div className="bg-[#F4F4F6]">
          <div className="space-y-[32px] flex flex-col justify-between p-4 bg-white rounded-[8px]">
            {/* === SAP MODAL === */}
            <SAPMaterialModal
              isOpen={showSAPModal}
              onClose={() => setShowSAPModal(false)}
              materialCode={MaterialCode || ""}
              materialDescription={
                MaterialOnboardingDetails?.material_request_item?.material_name_description || ""
              }
              isZCAPMaterial={isZCAPMaterial}
            />

            {/* === SECTIONS === */}
            <RequesterDetails MaterialOnboardingDetails={MaterialOnboardingDetails} form={form} />

            <MaterialInformation
              {...props}
              setShouldShowAllFields={setShouldShowAllFields}
              shouldShowAllFields={shouldShowAllFields}
              isMaterialCodeEdited={isMaterialCodeEdited}
              setIsMaterialCodeEdited={setIsMaterialCodeEdited}
              setIsMatchedMaterial={setIsMatchedMaterial}
              isZCAPMaterial={isZCAPMaterial}
            />

            {shouldShowAllFields && (
              <>
                {["CP", "Store"].includes(role) && (
                  <>
                    <MaterialPurchasingData {...props} role={role} />

                    <MaterialMRPData {...props} role={role} isZCAPMaterial={isZCAPMaterial} />

                    {!isZCAPMaterial && (
                      <MaterialQAQCData {...props} role={role} isZCAPMaterial={isZCAPMaterial} />
                    )}

                    <MaterialSpecifications {...props} role={role} isZCAPMaterial={isZCAPMaterial} />

                    <MaterialOtherData
                      {...props}
                      filteredProfit={filteredProfit}
                      setFilteredProfit={setFilteredProfit}
                      fileSelected={fileSelected}
                      setFileSelected={setFileSelected}
                      fileName={fileName}
                      setFileName={setFileName}
                      handleLabelClick={handleLabelClick}
                      handleImageChange={handleImageChange}
                      handleRemoveFile={handleRemoveFile}
                      isZCAPMaterial={isZCAPMaterial}
                    />
                    <MaterialComment {...props} />
                    <MaterialOnboardingApproval {...props} />
                  </>
                )}
              </>
            )}

            {/* === FOOTER BUTTONS === */}
            <div className="flex justify-between items-center w-full mt-4">
              {role === "User" && isSAPLockedStatus ? (
                <div className="flex justify-end w-full">
                  <Button variant="backbtn" size="backbtnsize" onClick={onCancel} type="button">
                    Back to Home
                  </Button>
                </div>
              ) : isMatchedMaterial ? (
                <>
                  <Button variant="backbtn" size="backbtnsize" onClick={onCancel} type="button">
                    Back to Home
                  </Button>
                  <div className="flex space-x-5 items-center">
                    <Button variant="backbtn" size="backbtnsize" type="button" onClick={() => setShowRemarkDialog(true)}>
                      Revert
                    </Button>
                    <Button
                      variant="nextbtn"
                      size="nextbtnsize"
                      type="button"
                      onClick={() => {
                        if (onCloseCallback && doc_name) onCloseCallback(doc_name);
                      }}
                    >
                      {isLoading ? "Processing..." : "Use Existing Material Code"}
                    </Button>
                  </div>
                </>
              ) : (
                <>
                  <Button variant="backbtn" size="backbtnsize" onClick={onCancel} type="button">
                    Back
                  </Button>
                  <div className="flex space-x-5 items-center">
                    <Button variant="backbtn" size="backbtnsize" type="button" onClick={() => setShowRemarkDialog(true)}>
                      Revert
                    </Button>
                    <Button
                      variant="nextbtn"
                      size="nextbtnsize"
                      type="submit"
                      onClick={handleApprovalStatus}
                    >
                      {isLoading ? "Processing..." : getButtonLabel(role, approvalStatus)}
                    </Button>
                  </div>
                </>
              )}

              {showAlert && (
                <Alertbox
                  content="Your Details have been submitted successfully!"
                  submit={showAlert}
                  url="/material-onboarding-table"
                />
              )}

              {showcompletealert && (
                <Alertbox
                  content="Your ticket to create new Material Code has been successfully closed!"
                  submit={showcompletealert}
                  url="/material-onboarding-table"
                />
              )}

              <RevertRemarkModal
                isOpen={showRemarkDialog}
                onClose={() => setShowRemarkDialog(false)}
                onConfirm={async (remark) => {
                  handleRejectStatus(remark);
                  if (sendRevertEmail && doc_name) {
                    await sendRevertEmail(doc_name, remark);
                    setShowRemarkDialog(false);
                  }
                }}
              />

              {showRevertAlert && (
                <Alertbox
                  content="Your ticket has been successfully re-opened with the remark!"
                  submit={showRevertAlert}
                  url="/material-onboarding-table"
                />
              )}
            </div>
          </div>

          {/* === Floating Save Button === */}
          {saveAsDraft && (
            <div className="fixed right-0 bottom-20 z-50 group">
              <button
                type="button"
                onClick={saveAsDraft}
                className="bg-[#5291CD] text-white rounded-full p-3 shadow-lg hover:bg-[#407ab0] transition-all duration-200 relative"
              >
                <Save className="w-5 h-5" />
                <span className="absolute -top-10 left-1/2 -translate-x-1/2 whitespace-nowrap bg-black text-white text-xs px-2 py-1 rounded opacity-0 group-hover:opacity-100 transition-all duration-300 pointer-events-none">
                  Save as Draft
                </span>
              </button>
            </div>
          )}
        </div>
      </form>
    </Form>
  );
};

export default MaterialOnboardingForm;
