export type QuotationDetail = {
  name: string;
  rfq_number: string;
  vendor_code: string | null;
  quote_amount: string | null;
  rank: string | null;
  mode_of_shipment: string;
  office_email_primary: string | null;
  airlinevessel_name: string;
  chargeable_weight: string;
  ratekg: string;
  fuel_surcharge: string;
  destination_port: string;
  actual_weight: string;
  sc: string;
  xray: string;
  pickuporigin: string | null;
  ex_works: string | null;
  total_freight: string;
  from_currency: string | null;
  to_currency: string | null;
  exchange_rate: string | null;
  total_freightinr: string | null;
  destination_charge: string | null;
  shipping_line_charge: string | null;
  cfs_charge: string | null;
  total_landing_price: string | null;
  invoice_no: string;
  transit_days: string | null;
  other_charges_in_total:string;
  expected_delivery_in_no_of_days:string;
  remarks:string;
  vendor_name:string;
  attachments:DocumentAttachment[]
};
export type DocumentAttachment = {
  document_name: string;
  attach: string;
  file_url: string;
};
