"use client";

import Image from "next/image";
import { TvendorRegistrationDropdown } from "@/src/types/types";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import API_END_POINTS from "@/src/services/apiEndPoints";
import { useEffect, useState } from "react";
import { useAuth } from "@/src/context/AuthContext";
import UserDashboardTable from "./Material-Onboarding-Table/Material-Onboarding-User-Table";
import CPDashboardTable from "./Material-Onboarding-Table/Material-Onboarding-CP-table";
import { cardCount } from "../pages/MaterialOnboardingDashboard";
import requestWrapper from "@/src/services/apiCall";
import { MaterialRequestItem } from "@/src/types/MaterialRequestTableTypes";

type Props = {
  cardData: cardCount;
  companyDropdown: TvendorRegistrationDropdown["message"]["data"]["company_master"];
};

const MaterialOnboardingCards = ({ cardData, companyDropdown }: Props) => {
  const { designation } = useAuth();
  const [loading, setLoading] = useState<boolean>(false);
  const [allData, setAllData] = useState<MaterialRequestItem[]>([]);
  const [activeTab, setActiveTab] = useState<string>("Total Material Request");
  const [currentPage, setCurrentPage] = useState<number>(1);
  const [totalRecords, setTotalRecords] = useState<number>(0);
  const recordPerPage = 20;

  const CPUser = designation === "Material CP";

  const fetchTableData = async (tabName: string, page: number) => {
    setLoading(true);
    try {
      const APPROVED_STATUSES = ["Code Generated by SAP"];
      let filters: any = {};

      if (tabName === "Approved Material Request") {
        filters.approval_status = ["in", APPROVED_STATUSES];
      } else if (tabName === "Pending Material Request") {
        filters.approval_status = ["not in", APPROVED_STATUSES];
      }

      const url = `${API_END_POINTS.getRequestorMasterTableList}?limit=${recordPerPage}&offset=${(page - 1) * recordPerPage}&filters=${encodeURIComponent(JSON.stringify(filters))}&_t=${Date.now()}`;
      const response = await requestWrapper({
        url: url,
        method: "GET",
      });

      const resData = response.data?.message?.data || response.data?.data || [];
      const pagination = response.data?.message?.pagination || response.data?.pagination;

      setAllData(resData);

      if (pagination && pagination.total_count !== undefined) {
        setTotalRecords(pagination.total_count);
      } else {
        const fallbackCount = resData.length + (resData.length === recordPerPage ? 1 : 0);
        setTotalRecords(fallbackCount);
      }
    } catch (err) {
      console.error("Error fetching data:", err);
    } finally {
      setLoading(false);
    }
  };

  const allCardData = [
    {
      name: "Total Material Request",
      count: cardData?.total_count ?? 0,
      icon: "/dashboard-assests/cards_icon/file-search.svg",
      text_color: "text-violet-800",
      bg_color: "bg-violet-100",
      hover: "hover:border-violet-400",
    },
    {
      name: "Pending Material Request",
      count: cardData?.pending ?? 0,
      icon: "/dashboard-assests/cards_icon/file-search.svg",
      text_color: "text-rose-800",
      bg_color: "bg-rose-100",
      hover: "hover:border-rose-400",
    },
    {
      name: "Approved Material Request",
      count: cardData?.approved ?? 0,
      icon: "/dashboard-assests/cards_icon/file-search.svg",
      text_color: "text-emerald-800",
      bg_color: "bg-emerald-100",
      hover: "hover:border-emerald-400",
    },
  ];

  useEffect(() => {
    fetchTableData(activeTab, currentPage);
  }, [activeTab, currentPage]);

  const handleTabChange = (val: string) => {
    setActiveTab(val);
    setCurrentPage(1);
  }

  return (
    <div>
      <Tabs value={activeTab} onValueChange={handleTabChange} className="">
        <TabsList className="grid grid-cols-3 gap-4 h-full pb-6 bg-white">
          {allCardData.map((item) => (
            <TabsTrigger
              key={item.name}
              value={item.name}
              className="data-[state=active]:bg-white data-[state=active]:shadow-md data-[state=active]:text-black text-gray-500 rounded-2xl p-0 transition-all duration-300 ease-in-out"
            >
              <div
                className={`group w-full h-full rounded-2xl ${item.bg_color} flex flex-col p-3 ${item.text_color} justify-between border-2 ${item.hover} hover:scale-105 transition duration-300 transform cursor-pointer shadow-md`}
              >
                <div className="flex w-full justify-between">
                  <h1 className="text-[13px]">{item.name}</h1>
                  <Image src={item.icon} alt="" width={25} height={30} />
                </div>
                <div className="text-[20px] text-start font-bold">{item.count}</div>
              </div>
            </TabsTrigger>
          ))}
        </TabsList>

        {allCardData.map((item) => (
          <TabsContent key={item.name} value={item.name} className="relative minimax-h-[400px]">
            {loading && (
              <div className="absolute inset-0 z-10 flex items-center justify-center bg-white/50 backdrop-blur-[1px]">
                <div className="flex flex-col items-center gap-2 font-medium text-blue-600">
                  <div className="h-8 w-8 animate-spin rounded-full border-4 border-blue-600 border-t-transparent"></div>
                  <span>Loading...</span>
                </div>
              </div>
            )}

            {CPUser ? (
              <CPDashboardTable
                data={allData}
                companyDropdown={companyDropdown}
                TableTitle={item.name}
                currentPage={currentPage}
                setCurrentPage={setCurrentPage}
                totalRecords={totalRecords}
                recordPerPage={recordPerPage}
              />
            ) : (
              <UserDashboardTable
                data={allData}
                companyDropdown={companyDropdown}
                TableTitle={item.name}
                currentPage={currentPage}
                setCurrentPage={setCurrentPage}
                totalRecords={totalRecords}
                recordPerPage={recordPerPage}
              />
            )}
          </TabsContent>
        ))}
      </Tabs>
    </div>
  );
};

export default MaterialOnboardingCards;