import { Button } from "@/components/ui/button";

interface Props {
  isFirstTab: boolean;
  isLastTab: boolean;
  isLoading?: boolean;
  role: string;
  approvalStatus?: string;
  onNext: () => void;
  onPrev: () => void;
  onCancel: () => void;
  onSubmit: () => void;
  onRevert: () => void;
  onUseExisting?: () => void;
  saveAsDraft?: () => void;
  getButtonLabel: (role: string, status?: string) => string;
  isRevisedNewCode?: boolean;
}

export default function MaterialFormFooter(props: Props) {
  const {
    isFirstTab,
    isLastTab,
    isLoading,
    role,
    approvalStatus,
    onNext,
    onPrev,
    onCancel,
    onSubmit,
    onRevert,
    onUseExisting,
    saveAsDraft,
    getButtonLabel = () => "Submit",
    isRevisedNewCode = true,
  } = props;

  const hideDraft =
    approvalStatus === "Sent to SAP" ||
    approvalStatus === "Code Generated by SAP";

  const isUseExistingCode = approvalStatus === "Use Existing Code";

  return (
    <div className="flex justify-between items-center w-full mt-4">

      {/* Back Button (Always Left) */}
      <Button
        variant="backbtn"
        size="backbtnsize"
        onClick={isFirstTab ? onCancel : onPrev}
        type="button"
      >
        Back
      </Button>

      {/* Right Side Buttons */}
      <div className="flex space-x-5">

        {/* NON LAST TAB */}
        {!isLastTab && (
          <>
            {!hideDraft && (
              <Button
                variant="backbtn"
                size="backbtnsize"
                onClick={saveAsDraft}
                type="button"
              >
                Save as Draft
              </Button>
            )}

            <Button
              variant="nextbtn"
              size="nextbtnsize"
              onClick={onNext}
            >
              Next
            </Button>
          </>
        )}

        {/* LAST TAB */}
        {isLastTab && (
          <>
            {!isUseExistingCode && (
              <Button
                variant="backbtn"
                size="backbtnsize"
                onClick={onRevert}
              >
                Revert
              </Button>
            )}
            {!isRevisedNewCode ? (
              !isUseExistingCode && (
                <Button
                  variant="nextbtn"
                  size="nextbtnsize"
                  onClick={onUseExisting}
                >
                  Use Existing Material Code
                </Button>
              )
            ) : (
              <>
                {!hideDraft && (
                  <Button
                    variant="backbtn"
                    size="backbtnsize"
                    onClick={saveAsDraft}
                    type="button"
                  >
                    Save as Draft
                  </Button>
                )}

                <Button
                  variant="nextbtn"
                  size="nextbtnsize"
                  disabled={isLoading}
                  onClick={onSubmit}
                >
                  {isLoading
                    ? "Processing..."
                    : getButtonLabel(role, approvalStatus)}
                </Button>
              </>
            )}
          </>
        )}
      </div>
    </div>
  );
}