const url = process.env.NEXT_PUBLIC_BACKEND_END;

export const QUICK_VENDOR_END_POINTS = {
    getVendorTypeMasterList: `${url}/api/method/vms.utils.master_data.get_vendor_type_master_list`,
    getCompanyCodesBySessionUser: `${url}/api/method/vms.utils.master_data.get_company_codes_by_session_user`,
    getPurchaseOrgMasterData: `${url}/api/method/vms.utils.master_data.get_purchase_org_master_data`,
    getCurrencyMasterList: `${url}/api/method/vms.utils.master_data.get_currency_master_list`,
    getAccountGroupMasterData: `${url}/api/method/vms.utils.master_data.get_account_group_master_data`,
    getPincodeMaster: `${url}/api/method/vms.utils.master_data.get_pincode_master`,
    getLocationByPincode: `${url}/api/method/vms.utils.master_data.get_location_by_pincode`,
    getReconciliationMasterData: `${url}/api/method/vms.utils.master_data.get_reconciliation_master_data`,
    getTermsOfPaymentMasterData: `${url}/api/method/vms.utils.master_data.get_terms_of_payment_master_data`,
    getCountryMasterList: `${url}/api/method/vms.utils.master_data.get_country_master_list`,
    getBankKeyMasterData: `${url}/api/method/vms.utils.master_data.get_bank_key_master_data`,
    getStateMasterList: `${url}/api/method/vms.utils.master_data.get_state_master_list`,
    createQuickVendorOnboarding: `${url}/api/method/vms.APIs.quick_onboarding.v1.vendor_registration.vendor_registration`,
    getQuickVendorOnboardingDetails: `${url}/api/method/vms.APIs.quick_onboarding.v1.quick_vendor_onboarding_details.get_quick_vendor_onboarding_details`,
    getIncotermsMasterData: `${url}/api/method/vms.utils.master_data.get_incoterms_master_data`,
    updateGstDetail: `${url}/api/method/vms.APIs.quick_onboarding.v1.update_gst_detail.update_gst_details`,
    updateContactDetail: `${url}/api/method/vms.APIs.quick_onboarding.v1.update_contact_person.update_contact_detail`,
    deleteContactDetailRow: `${url}/api/method/vms.APIs.quick_onboarding.v1.update_contact_person.delete_contact_detail_row`,
    updateDomesticBankDetails: `${url}/api/method/vms.APIs.quick_onboarding.v1.update_domestic_bank_details.update_domestic_bank_details`,
    deleteDomesticBankDetailRow: `${url}/api/method/vms.APIs.quick_onboarding.v1.update_domestic_bank_details.delete_domestic_bank_detail_row`,
    updateImportBankDetails: `${url}/api/method/vms.APIs.quick_onboarding.v1.update_import_bank_details.update_import_bank_details`,
    deleteImportBankDetailRow: `${url}/api/method/vms.APIs.quick_onboarding.v1.update_import_bank_details.delete_import_bank_detail_row`,
    submitOnboardingForm: `${url}/api/method/vms.APIs.quick_onboarding.v1.vendor_registration.submit_onboarding_form`,
    deleteGstDetailRow: `${url}/api/method/vms.APIs.quick_onboarding.v1.update_gst_detail.delete_gst_detail_row`,
    accountsTeamApproval: `${url}/api/method/vms.APIs.quick_onboarding.v1.quick_onboarding_approval.accounts_team_approval`,
    getQuickOnboardingRequesterRecords: `${url}/api/method/vms.APIs.quick_onboarding.v1.vendor_request_dashboard.get_quick_onboarding_requester_records`,
    getQuickOnboardingApprovalRecords: `${url}/api/method/vms.APIs.quick_onboarding.v1.vendor_approval_dashboard.get_quick_onboarding_approval_records`,
}
